### ISSUE TITLE
Not working in Chrome

### ISSUE THREAD

**Issue by ekansa** [sniku/jQuery-doubleScroll#3]
Hi, I'm trying to get this to work in Chrome (testing on Windows 7 machine). The example HTML gives two scroll bars, but with Chrome, the horizontal scroll bars always moves back to the left-most position, so the large table can't be navigated horizontally.

Any ideas on why?

Thanks!

**Comment by sniku** [comment]
Hi!

Does it work for you on the demo page? http://suwala.eu/blog/2012/02/01/horizontal-scrollbar-top-and-bottom-element/
I suspect that your "wide element" is not the first child of the wrapper, in that case try this:

$(document).ready(function(){
       $('#double-scroll').doubleScroll({contentElement: $('.selector_to_the_widest_element_in_the_wrapper_here') });
});

Let me know if it worked for you

**Comment by ekansa** [comment]
Thanks for helping with this! It turns out the problem only exists when I was running this on my localhost. I got it working nicely with a remote server, and thanks for the tip in selecting the widest dom element.

It's working like a charm!

**Comment by marceloloureiro** [comment]
I've got the same problem.

In google chrome, if you give one zoom out in the page (press Ctrl + subtract key once), the problem happens.

I'm using Chrome version  25.0.1364.97

**Comment by sniku** [comment]
Does it work for you on the demo page? http://suwala.eu/blog/2012/02/01/horizontal-scrollbar-top-and-bottom-element/

If it works, can you provide a link to your implementation?

**Comment by ekansa** [comment]
Hi All. Yep. Happening to me too at different zoom levels in Chrome. Not just a local host problem.

Example:
http://opencontext.org/tables/0ff5a5f1fa28b7f928562e67836a575a

But the demo page seems to work at different zoom levels in Chrome. Huh. Am I doing something funny?

Thanks!
-E

**Comment by marceloloureiro** [comment]
No, it doesn't work.

But seems to be a chrome's bug. I've already open a issue in the chromium
project: https://code.google.com/p/chromium/issues/detail?id=238718

Thanks,
Marcelo

2013/5/29 Eric Kansa notifications@github.com

**Comment by avianey** [comment]
this enhanced version works well in Chrome : https://github.com/avianey/jqDoubleScroll

**Comment by sniku** [comment]
Hi avianey,

it would be great if you could make a push request with your changes. Otherwise we will have a nasty fork-fragmentation of this code. Thanks
