### ISSUE TITLE
how to manual refresh?

### ISSUE THREAD

**Issue by ryan2johnson9** [sniku/jQuery-doubleScroll#6]
Hi,

for me the 'refresh' call was not being made when the content (table) increased in size(show hiding columns). I have a jquery Datatable in the content which dynamically shows/hides columns and the refresh in the doubleScroll code was not getting triggered. (Firefox/Chromium/Chrome)

I fixed this with a hack in the _create method in your code by setting the doubleScroll object (this) to a variable I could access elsewhere and then calling .refresh() maually. But is there a better way? 

The result of the 

```
$('double-scroll').doubleScroll()
```

 call returns a jquery element so I cannot do the following:

```
var el = $('double-scroll').doubleScroll();
el.refresh()
```

**Comment by sniku** [comment]
That's a nice hack - exactly what the refresh function was made for.
Plugin in itself isn't listening to DOM changes, so you need to call this function after your element was resized.

**Comment by ryan2johnson9** [comment]
Ok, thanks @sniku
